// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramTracker;

namespace ProgramTracker.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20200809000504_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProgramTracker.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Elapsed")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("User")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ProgramId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("ProgramTracker.Timerange", b =>
                {
                    b.Property<int>("TimerangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProgramId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProgramId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TimerangeId");

                    b.HasIndex("ProgramId1");

                    b.ToTable("Timeranges");
                });

            modelBuilder.Entity("ProgramTracker.Timerange", b =>
                {
                    b.HasOne("ProgramTracker.Program", null)
                        .WithMany("Timeranges")
                        .HasForeignKey("ProgramId1");
                });
#pragma warning restore 612, 618
        }
    }
}
